var chatNameDisplay=document.createElement('div')
chatNameDisplay.style.position='absolute'
chatNameDisplay.style.overflow='visible'
chatNameDisplay.style.width='250px'
chatNameDisplay.style.height='50px'
chatNameDisplay.style.left='1150px'
chatNameDisplay.style.top='80px'
chatNameDisplay.style.fontSize='18px'
chatNameDisplay.style.border="2px solid black"
